name: Node.js CI

on:
    push:
        branches: 
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 16, 18, 20 ]
            fail-fast: false

        name: Node.js ${{ matrix.node-version }} CI
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Docker image
              run : |
                docker build --build-arg NODE_VERSION=${{ matrix.node-version }} -t nodejs-express-ci-app:${{ matrix.node-version }} .

            - name: Run tests in Docker
              run: |
                docker run --rm nodejs-express-ci-app:${{ matrix.node-version }} npm test
                
